---
abstract: 'Transfirst eLink backend for Business::OnlinePayment'
author:
  - 'Jeff Finucane <transfirst@weasellips.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-OnlinePayment-TransFirsteLink
no_index:
  directory:
    - t
    - inc
requires:
  Business::OnlinePayment: 3
  Business::OnlinePayment::HTTPS: 0.05
  Tie::IxHash: 0
version: 0.05
