# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Business-OnlinePayment-TransFirsteLink
version:      0.02
version_from: TransFirsteLink.pm
installdirs:  site
requires:
    Business::OnlinePayment:       3
    Business::OnlinePayment::HTTPS: 0.05
    Tie::IxHash:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
